#!/usr/bin/env python3
import unittest
import os
import networkit as nk
import tempfile

class TestGEXFIO(unittest.TestCase):
	def setUp(self):
		from networkit.GEXFIO import GEXFReader
		from networkit.graph import Graph
		self.reader = GEXFReader()
		#celegans.gexf from http://gexf.net/format/datasets.html
		self.g, self.events = self.reader.read("input/staticTest.gexf")
		#dynamics.gexf from http://gexf.net/format/datasets.html
		self.g2, self.events2 = self.reader.read("input/dynamicTest.gexf")
		#a random dynamic gexf file generated by gephi with dynamic weights
		self.g3, self.events3 = self.reader.read("input/dynamicTest2.gexf")
		#a simple dynamic weighted graph
		self.g4, self.events4 = self.reader.read("input/dynamicTest3.gexf")

	def checkStatic(self, graph, graph2):
		self.assertEqual(graph.isDirected(), graph2.isDirected())
		self.assertEqual(graph.isWeighted(), graph2.isWeighted())
		self.assertEqual(graph.numberOfNodes(), graph2.numberOfNodes())
		self.assertEqual([(u, v) for u, v in graph.iterEdges()], [(u, v) for u, v in graph2.iterEdges()])

	def checkDynamic(self, eventStream, eventStream2):
		from networkit.dynamics import GraphEvent
		self.assertEqual(len(eventStream), len(eventStream2))
		#Check if timesteps are occuring at the same indexes
		index = 0
		for i in range(0, len(eventStream)):
			event = eventStream[i]
			event2 = eventStream2[i]
			if event.type == GraphEvent.TIME_STEP:
				self.assertEqual(GraphEvent.TIME_STEP, event2.type)
				old_index = index
				index = i
				#check if # of events between each timestep is equal
				self.assertEqual(len(eventStream[old_index:index]),
					len(eventStream2[old_index:index]))

	def test_read_and_write(self):
		#write and read files again to check
		from networkit.GEXFIO import GEXFWriter
		writer = GEXFWriter()

		with tempfile.TemporaryDirectory() as tmpdir:
			graphs = [self.g, self.g2, self.g3, self.g4]
			events = [self.events, self.events2, self.events3, self.events4]

			for g, events in zip(graphs, events):
				resultsPath = os.path.join(tmpdir, "results.gexf")
				writer.write(g, resultsPath, events)
				self.assertTrue(os.path.isfile(resultsPath))

				gTest, testEvents = self.reader.read(resultsPath)

				#1. check properties and static elements
				self.checkStatic(g, gTest)

				#2.check events
				self.checkDynamic(events, testEvents)

	def testWriteGraphReadGraph(self):
		G = nk.generators.ErdosRenyiGenerator(100, 0.1).generate()
		someFailed = False

		excluded_formats = set([nk.Format.KONECT, nk.Format.DOT, nk.Format.GraphViz, nk.Format.SNAP])

		for format in nk.Format:
			if format in excluded_formats:
				# format do not support both reading and writing
				continue

			with tempfile.TemporaryDirectory() as tmpdir:
				filename = "testWriteGraphReadGraph." + str(format)
				if format == nk.Format.MAT:
					filename += ".mat" # suffix required
				path = os.path.join(tmpdir, filename)

				kargs = [' ', 0] if format == nk.Format.EdgeList else []
				nk.graphio.writeGraph(G, path, format, *kargs)
				if format == nk.Format.GEXF:
					G1, _ = nk.graphio.readGraph(path, format, *kargs)
				else:
					G1 = nk.graphio.readGraph(path, format, *kargs)
				self.checkStatic(G, G1)


if __name__ == "__main__":
	unittest.main()
