#ifndef NETWORKIT_COMPONENTS_DYN_WEAKLY_CONNECTED_COMPONENTS_HPP_
#define NETWORKIT_COMPONENTS_DYN_WEAKLY_CONNECTED_COMPONENTS_HPP_
#include <networkit/components/DynConnectedComponents.hpp>
#warning "DynWeaklyConnectedComponents.hpp is deprecated, use DynConnectedComponents.hpp instead."
#endif // NETWORKIT_COMPONENTS_DYN_WEAKLY_CONNECTED_COMPONENTS_HPP_
